### ISSUE TITLE
More Details

### ISSUE THREAD

**Issue by Molowogan85** [mlcsec/headi#1]
How can it be redirected to another url/Link.Just help with the command please.

**Comment by mlcsec** [comment]
All information on tool functionality is in the readme

**Comment by Molowogan85** [comment]
I'm trying to figure it out. -pfile addr?The ip you use/redirected to (192.168.4.28),is it the addr?Or you created a file named addr?Or you edited main.go and add the ip/url you redirected to.Kindly give me straight forward answer.

**Comment by mlcsec** [comment]
The `addr` file contained the IP `192.168.4.28` which is then injected into the tested headers.  I'll be closing this issue, the readme section and the tool help (`-h`) states that `-pfile` is the payload file parameter.
