### ISSUE TITLE
Installation Issue on Ubuntu

### ISSUE THREAD

**Issue by himmat1005** [mlcsec/headi#14]
Have been trying for a while but it is not working :

root@ubuntu-s-1vcpu-1gb-blr1-01:~/999.bash-scripts# git clone https://github.com/mlcsec/headi
Cloning into 'headi'...
remote: Enumerating objects: 122, done.
remote: Counting objects: 100% (19/19), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 122 (delta 10), reused 6 (delta 6), pack-reused 103
Receiving objects: 100% (122/122), 36.58 KiB | 1.59 MiB/s, done.
Resolving deltas: 100% (32/32), done.

root@ubuntu-s-1vcpu-1gb-blr1-01:~/999.bash-scripts# cd headi

root@ubuntu-s-1vcpu-1gb-blr1-01:~/999.bash-scripts/headi# make before.build
go mod init v0 && go mod tidy
go: creating new go.mod: module v0
go: finding module for package github.com/fatih/color
go: found github.com/fatih/color in github.com/fatih/color v1.13.0
go mod download && go mod vendor

root@ubuntu-s-1vcpu-1gb-blr1-01:~/999.bash-scripts/headi# make.build-headi
-bash: make.build-headi: command not found

root@ubuntu-s-1vcpu-1gb-blr1-01:~/999.bash-scripts/headi# make build-headi
make: *** No rule to make target 'build-headi'.  Stop.

**Comment by mlcsec** [comment]
updated git build commands in the readme, tested and working on Ubuntu 22.04
