### ISSUE TITLE
Multiple Targets Failed

### ISSUE THREAD

**Issue by Molowogan85** [mlcsec/headi#5]
I like your work,its really on point.My problem is that i tried to target multiple ip,instead of redirecting to only one address but it failed.Can you work on it or people should bring ideas in order to automate and redirect to multiple ip/addresses.

**Comment by mlcsec** [comment]
Can you provide more detail on what you're trying to do

**Comment by Molowogan85** [comment]
I have multiple ip/targets im doing for pentesting,and im trying to perform header injection on them.I find it time consuming if im redirecting them to my target.com one at a time.Summary of what i mean is "Mass header injection" to about 3 to 5 ip at a time.

**Comment by mlcsec** [comment]
As per the last issue you opened, this is not a problem with the tool but with the person using it.  As stated in the readme:

Currently only takes one URL as input but you can easily bash script for numerous URLs like so:
```
$ for i in $(cat urls); do headi -url $i;done
```
